export enum Msg {
  INIT = "capturebliss/INIT",
  WIN_RESIZE = "capturebliss/WIN_RESIZE",
  WIN_ON_RESIZE = "capturebliss/WIN_ON_RESIZE",
  INITED = "capturebliss/INITED",
  SCRIPT_INIT = "capturebliss/SCRIPT_INIT",
  SCRIPT_INIT_DATA = "capturebliss/SCRIPT_INIT_DATA",
  ADD_SAMPLE_USER = "capturebliss/ADD_SAMPLE_USER",
  SAVE_SCREEN = "capturebliss/SAVE_SCREEN",
  SERIALIZE_FRAME = "capturebliss/SERIALIZE_FRAME",
  FRAME_SERIALIZED = "capturebliss/FRAME_SERIALIZED",
  FRAME_SERIALIZATION_START = "capturebliss/FRAME_SERIALIZATION_START",
  START_RECORDING = "capturebliss/START_RECORDING",
  STOP_RECORDING = "capturebliss/STOP_RECORDING",
  RESET_STATE = "capturebliss/RESET_STATE",
  DELETE_RECORDING = "capturebliss/DELETE_RECORDING",
  OPEN_LINK_IN_NEW_TAB = "capturebliss/OPEN_LINK_IN_NEW_TAB",
  TAKE_SCREENSHOT = "capturebliss/TAKE_SCREENSHOT",
  CLIENT_CONTENT_INIT = "capturebliss/CLIENT_CONTENT_INIT",
  SAVE_TOUR_DATA = "capturebliss/SAVE_TOUR_DATA",
  SAVE_SCREENS_DATA_IN_EXCHANGE_DIV = "capturebliss/SAVE_SCREENS_DATA",
  SAVE_COOKIES_DATA_IN_EXCHANGE_DIV = "capturebliss/SAVE_COOKIES_DATA",
  SAVE_TOTAL_SCREEN_COUNT_IN_EXCHANGE_DIV = "capturebliss/SAVE_TOTAL_SCREEN_COUNT_IN_EXCHANGE_DIV",
  SAVE_STYLE_DATA = "capturebliss/SAVE_STYLE_DATA",
  SAVE_VERSION_DATA="capturebliss/SAVE_VERSION_DATA",
  REINJECT_CONTENT_SCRIPT = "REINJECT_CONTENT_SCRIPT",
  RECORDING_CREATE_OR_DELETE_COMPLETED = "RECORDING_CREATE_OR_DELETE_COMPLETED",
  SHOW_COUNTDOWN_MODAL = "SHOW_COUNTDOWN_MODAL",
  INIT_REGISTERED_CONTENT_SCRIPTS="capturebliss/INIT_REGISTERED_CONTENT_SCRIPTS",
  __TEST__ = "capturebliss/__test__"
}

export interface MsgPayload<T> {
  type: Msg;
  data: T;
}
